quarkus.http.port=8081

quarkus.langchain4j.timeout=60s

quarkus.langchain4j.mcp.pg_query.transport-type=streamable-http
quarkus.langchain4j.mcp.pg_query.url=${MCP_PG_QUERY_URL:http://localhost:8080/mcp}

quarkus.langchain4j.chat-model.provider=openai
quarkus.langchain4j.openai.chat-model.temperature=0.2
quarkus.langchain4j.openai.base-url=${OPENAI_BASE_URL:http://localhost:8000/v1}
quarkus.langchain4j.openai.chat-model.model-name=${OPENAI_MODEL_NAME:qwen25-14b-tools}

quarkus.vertx.max-event-loop-execute-time=20S
quarkus.vertx.max-worker-execute-time=20S

quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p %s%e%n